/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Leap.Client;
using Leap.Api;
// uncomment below to import models
//using Leap.Model;

namespace Leap.Test.Api
{
    /// <summary>
    ///  Class for testing ImagesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ImagesApiTests : IDisposable
    {
        private ImagesApi instance;

        public ImagesApiTests()
        {
            instance = new ImagesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImagesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ImagesApi
            //Assert.IsType<ImagesApi>(instance);
        }

        /// <summary>
        /// Test Delete
        /// </summary>
        [Fact]
        public void DeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string modelId = null;
            //string inferenceId = null;
            //instance.Delete(modelId, inferenceId);
        }

        /// <summary>
        /// Test FindOne
        /// </summary>
        [Fact]
        public void FindOneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string modelId = null;
            //string inferenceId = null;
            //var response = instance.FindOne(modelId, inferenceId);
            //Assert.IsType<InferenceEntity>(response);
        }

        /// <summary>
        /// Test Generate
        /// </summary>
        [Fact]
        public void GenerateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string modelId = null;
            //CreateInferenceDto createInferenceDto = null;
            //var response = instance.Generate(modelId, createInferenceDto);
            //Assert.IsType<InferenceEntity>(response);
        }

        /// <summary>
        /// Test ListAll
        /// </summary>
        [Fact]
        public void ListAllTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string modelId = null;
            //bool? onlyFinished = null;
            //decimal? page = null;
            //decimal? pageSize = null;
            //var response = instance.ListAll(modelId, onlyFinished, page, pageSize);
            //Assert.IsType<List<InferenceEntity>>(response);
        }
    }
}
