# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Created by: https://tryleap.ai/
"""

from leap.paths.api_v1_images_models_model_id_inferences_inference_id.delete import Delete
from leap.paths.api_v1_images_models_model_id_inferences_inference_id.get import FindOne
from leap.paths.api_v1_images_models_model_id_inferences.post import Generate
from leap.paths.api_v1_images_models_model_id_inferences.get import ListAll


class ImagesApi(
    Delete,
    FindOne,
    Generate,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
