/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using System;
using Xunit;
using Leap.Client;
using Leap.Model;

namespace Leap.Test
{
    /// <remarks>
    /// Boilerplate for writing some simple tests
    /// </remarks>
    public class SimpleTests : IDisposable
    {
        public SimpleTests()
        {
            // Setup
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test Client Initialization
        /// </summary>
        [Fact]
        public void ClientTest()
        {

            LeapClient client = new LeapClient();
            // Configure custom BasePath if desired
            client.SetBasePath("https://api.tryleap.ai");
            // Configure Bearer token for authorization: bearer
            client.SetAccessToken("YOUR_BEARER_TOKEN");

            Assert.NotNull(client);
        }
    }
}
