/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import {
  ImagesApi,
  ImageModelsApi,
  MusicApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LeapCustom } from "./client-custom";

export class Leap extends LeapCustom {
  readonly images: ImagesApi;
  readonly imageModels: ImageModelsApi;
  readonly music: MusicApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.images = new ImagesApi(configuration);
    this.imageModels = new ImageModelsApi(configuration);
    this.music = new MusicApi(configuration);
  }

}
