/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import {
  GenerateImagesApi,
  GenerateMusicApi,
  TrainImageModelsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LeapCustom } from "./client-custom";

export class Leap extends LeapCustom {
  readonly generateImages: GenerateImagesApi;
  readonly generateMusic: GenerateMusicApi;
  readonly trainImageModels: TrainImageModelsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.generateImages = new GenerateImagesApi(configuration);
    this.generateMusic = new GenerateMusicApi(configuration);
    this.trainImageModels = new TrainImageModelsApi(configuration);
  }

}
