/*
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.leap.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateAndTrainModelDto
 */
public class CreateAndTrainModelDtoTest {
    private final CreateAndTrainModelDto model = new CreateAndTrainModelDto();

    /**
     * Model tests for CreateAndTrainModelDto
     */
    @Test
    public void testCreateAndTrainModelDto() {
        // TODO: test CreateAndTrainModelDto
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'subjectKeyword'
     */
    @Test
    public void subjectKeywordTest() {
        // TODO: test subjectKeyword
    }

    /**
     * Test the property 'subjectType'
     */
    @Test
    public void subjectTypeTest() {
        // TODO: test subjectType
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

    /**
     * Test the property 'imageSampleUrls'
     */
    @Test
    public void imageSampleUrlsTest() {
        // TODO: test imageSampleUrls
    }

    /**
     * Test the property 'imageSampleFiles'
     */
    @Test
    public void imageSampleFilesTest() {
        // TODO: test imageSampleFiles
    }

}
