/*
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.leap.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.leap.client.model.ModelV2Entity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ListModelsV2Response
 */
public class ListModelsV2ResponseTest {
    private final ListModelsV2Response model = new ListModelsV2Response();

    /**
     * Model tests for ListModelsV2Response
     */
    @Test
    public void testListModelsV2Response() {
        // TODO: test ListModelsV2Response
    }

    /**
     * Test the property 'models'
     */
    @Test
    public void modelsTest() {
        // TODO: test models
    }

}
