/*
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.leap.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelV2Entity
 */
public class ModelV2EntityTest {
    private final ModelV2Entity model = new ModelV2Entity();

    /**
     * Model tests for ModelV2Entity
     */
    @Test
    public void testModelV2Entity() {
        // TODO: test ModelV2Entity
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'subjectKeyword'
     */
    @Test
    public void subjectKeywordTest() {
        // TODO: test subjectKeyword
    }

    /**
     * Test the property 'subjectType'
     */
    @Test
    public void subjectTypeTest() {
        // TODO: test subjectType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'imageSamples'
     */
    @Test
    public void imageSamplesTest() {
        // TODO: test imageSamples
    }

}
