# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from leap import Leap

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        leap = Leap(
            # Defining the host is optional and defaults to https://api.tryleap.ai
            # See configuration.py for a list of all supported configuration parameters.
            host = "https://api.tryleap.ai",
        
            # Configure Bearer authorization (JWT): bearer
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(leap)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
