/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CreateMusicgenInferenceDto
 */
export interface CreateMusicgenInferenceDto {
    /**
     * A description of the music you want to generate.
     * @type {string}
     * @memberof CreateMusicgenInferenceDto
     */
    'prompt': string;
    /**
     * Select a mode, each option generates different results. Melody is best for melody, music is best for full songs
     * @type {string}
     * @memberof CreateMusicgenInferenceDto
     */
    'mode': CreateMusicgenInferenceDtoModeEnum;
    /**
     * Duration of the generated audio in seconds. Max 30 seconds.
     * @type {number}
     * @memberof CreateMusicgenInferenceDto
     */
    'duration': number;
}

type CreateMusicgenInferenceDtoModeEnum = 'melody' | 'music'


