/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CreateInferenceDto
 */
export interface CreateInferenceDto {
    /**
     * A text description of the image you what you want to generate.
     * @type {string}
     * @memberof CreateInferenceDto
     */
    'prompt': string;
    /**
     * A text description of what the image should try to avoid generating.
     * @type {string}
     * @memberof CreateInferenceDto
     */
    'negativePrompt'?: string;
    /**
     * How many steps the AI will take to generate the image. Lower is faster but less detailed, higher is slower more detailed.
     * @type {number}
     * @memberof CreateInferenceDto
     */
    'steps'?: number;
    /**
     * The width of the image to use for the inference. Must be a multiple of 8. For best results use 1024x1024 for SDXL, and 512x512 for other models.
     * @type {number}
     * @memberof CreateInferenceDto
     */
    'width'?: number;
    /**
     * The height of the image to use for the inference. Must be a multiple of 8. For best results use 1024x1024 for SDXL, and 512x512 for other models.
     * @type {number}
     * @memberof CreateInferenceDto
     */
    'height'?: number;
    /**
     * The number of images to generate, up to 4.
     * @type {number}
     * @memberof CreateInferenceDto
     */
    'numberOfImages'?: number;
    /**
     * The higher the prompt strength, the closer the generated image will be to the prompt. Must be between 0 and 30.
     * @type {number}
     * @memberof CreateInferenceDto
     */
    'promptStrength'?: number;
    /**
     * A random number to use as a seed when generating the image. This is helpful if you want to generate the same image multiple times. If you want to generate different images, keep this empty or provide a random number.
     * @type {number}
     * @memberof CreateInferenceDto
     */
    'seed'?: number;
    /**
     * An optional webhook URL that will be called with a POST request when the image generation request completes.
     * @type {string}
     * @memberof CreateInferenceDto
     */
    'webhookUrl'?: string;
}

