/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CreateAndTrainModelDto
 */
export interface CreateAndTrainModelDto {
    /**
     * Provide a name so you can more easily identify the model.
     * @type {string}
     * @memberof CreateAndTrainModelDto
     */
    'name'?: string;
    /**
     * This is the keyword you will use during image generation to trigger your custom subject. For example \"a photo of @me\".
     * @type {string}
     * @memberof CreateAndTrainModelDto
     */
    'subjectKeyword'?: string;
    /**
     * The subject type - a short description, usually a noun, that describes what the underlying model is learning. For example: person, man, woman, cat, dog, icon, style. Defaults to \"person\".
     * @type {string}
     * @memberof CreateAndTrainModelDto
     */
    'subjectType'?: string;
    /**
     * An optional webhook URL that will be called with a POST request when the model completes training or fails.
     * @type {string}
     * @memberof CreateAndTrainModelDto
     */
    'webhookUrl'?: string;
    /**
     * An array of strings containing the URLs of the images to upload. Either this or imageSampleFiles is required, but not both.
     * @type {Array<string>}
     * @memberof CreateAndTrainModelDto
     */
    'imageSampleUrls'?: Array<string>;
    /**
     * An array of files containing the images to upload. Either this or imageSampleUrls is required, but not both.
     * @type {Array<Uint8Array | File>}
     * @memberof CreateAndTrainModelDto
     */
    'imageSampleFiles'?: Array<Uint8Array | File>;
}

