/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { InferenceImageEntity } from './inference-image-entity';

/**
 * 
 * @export
 * @interface InferenceEntity
 */
export interface InferenceEntity {
    /**
     * 
     * @type {string}
     * @memberof InferenceEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceEntity
     */
    'prompt': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceEntity
     */
    'negativePrompt': string;
    /**
     * 
     * @type {number}
     * @memberof InferenceEntity
     */
    'seed': number;
    /**
     * 
     * @type {number}
     * @memberof InferenceEntity
     */
    'width': number;
    /**
     * 
     * @type {number}
     * @memberof InferenceEntity
     */
    'height': number;
    /**
     * 
     * @type {number}
     * @memberof InferenceEntity
     */
    'promptStrength': number;
    /**
     * 
     * @type {number}
     * @memberof InferenceEntity
     */
    'numberOfImages': number;
    /**
     * 
     * @type {string}
     * @memberof InferenceEntity
     */
    'state': InferenceEntityStateEnum;
    /**
     * 
     * @type {number}
     * @memberof InferenceEntity
     */
    'steps': number;
    /**
     * 
     * @type {Array<InferenceImageEntity>}
     * @memberof InferenceEntity
     */
    'images': Array<InferenceImageEntity>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InferenceEntity
     */
    'modelId': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InferenceEntity
     */
    'upscalingOption': InferenceEntityUpscalingOptionEnum;
}

type InferenceEntityStateEnum = 'failed' | 'finished' | 'processing' | 'queued'
type InferenceEntityUpscalingOptionEnum = 'x1' | 'x2' | 'x4'


