/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface InferenceImageEntity
 */
export interface InferenceImageEntity {
    /**
     * 
     * @type {string}
     * @memberof InferenceImageEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceImageEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceImageEntity
     */
    'uri': string;
}

