/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ModelV2Entity } from './model-v2-entity';

/**
 * 
 * @export
 * @interface ListModelsV2Response
 */
export interface ListModelsV2Response {
    /**
     * 
     * @type {Array<ModelV2Entity>}
     * @memberof ListModelsV2Response
     */
    'models': Array<ModelV2Entity>;
}

