/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ModelV2Entity
 */
export interface ModelV2Entity {
    /**
     * 
     * @type {string}
     * @memberof ModelV2Entity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ModelV2Entity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ModelV2Entity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ModelV2Entity
     */
    'subjectKeyword': string;
    /**
     * 
     * @type {string}
     * @memberof ModelV2Entity
     */
    'subjectType': string;
    /**
     * 
     * @type {string}
     * @memberof ModelV2Entity
     */
    'status': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelV2Entity
     */
    'imageSamples': Array<string>;
}

