/* tslint:disable */
/* eslint-disable */
/**
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface MusicgenInferenceEntity
 */
export interface MusicgenInferenceEntity {
    /**
     * 
     * @type {string}
     * @memberof MusicgenInferenceEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MusicgenInferenceEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof MusicgenInferenceEntity
     */
    'prompt': string;
    /**
     * 
     * @type {string}
     * @memberof MusicgenInferenceEntity
     */
    'state': MusicgenInferenceEntityStateEnum;
    /**
     * 
     * @type {string}
     * @memberof MusicgenInferenceEntity
     */
    'media_uri'?: string;
}

type MusicgenInferenceEntityStateEnum = 'failed' | 'finished' | 'processing' | 'queued'


