/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Leap.Api;
using Leap.Model;
using Leap.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Leap.Test.Model
{
    /// <summary>
    ///  Class for testing CreateInferenceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateInferenceDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateInferenceDto
        //private CreateInferenceDto instance;

        public CreateInferenceDtoTests()
        {
            // TODO uncomment below to create an instance of CreateInferenceDto
            //instance = new CreateInferenceDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateInferenceDto
        /// </summary>
        [Fact]
        public void CreateInferenceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateInferenceDto
            //Assert.IsType<CreateInferenceDto>(instance);
        }


        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'NegativePrompt'
        /// </summary>
        [Fact]
        public void NegativePromptTest()
        {
            // TODO unit test for the property 'NegativePrompt'
        }
        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Fact]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'NumberOfImages'
        /// </summary>
        [Fact]
        public void NumberOfImagesTest()
        {
            // TODO unit test for the property 'NumberOfImages'
        }
        /// <summary>
        /// Test the property 'PromptStrength'
        /// </summary>
        [Fact]
        public void PromptStrengthTest()
        {
            // TODO unit test for the property 'PromptStrength'
        }
        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Fact]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }
        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Fact]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }

    }

}
