/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Leap.Api;
using Leap.Model;
using Leap.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Leap.Test.Model
{
    /// <summary>
    ///  Class for testing CreateMusicgenInferenceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateMusicgenInferenceDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateMusicgenInferenceDto
        //private CreateMusicgenInferenceDto instance;

        public CreateMusicgenInferenceDtoTests()
        {
            // TODO uncomment below to create an instance of CreateMusicgenInferenceDto
            //instance = new CreateMusicgenInferenceDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateMusicgenInferenceDto
        /// </summary>
        [Fact]
        public void CreateMusicgenInferenceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateMusicgenInferenceDto
            //Assert.IsType<CreateMusicgenInferenceDto>(instance);
        }


        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

    }

}
