/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Leap.Api;
using Leap.Model;
using Leap.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Leap.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAndTrainModelDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAndTrainModelDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAndTrainModelDto
        //private CreateAndTrainModelDto instance;

        public CreateAndTrainModelDtoTests()
        {
            // TODO uncomment below to create an instance of CreateAndTrainModelDto
            //instance = new CreateAndTrainModelDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAndTrainModelDto
        /// </summary>
        [Fact]
        public void CreateAndTrainModelDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAndTrainModelDto
            //Assert.IsType<CreateAndTrainModelDto>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SubjectKeyword'
        /// </summary>
        [Fact]
        public void SubjectKeywordTest()
        {
            // TODO unit test for the property 'SubjectKeyword'
        }
        /// <summary>
        /// Test the property 'SubjectType'
        /// </summary>
        [Fact]
        public void SubjectTypeTest()
        {
            // TODO unit test for the property 'SubjectType'
        }
        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Fact]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }
        /// <summary>
        /// Test the property 'ImageSampleUrls'
        /// </summary>
        [Fact]
        public void ImageSampleUrlsTest()
        {
            // TODO unit test for the property 'ImageSampleUrls'
        }
        /// <summary>
        /// Test the property 'ImageSampleFiles'
        /// </summary>
        [Fact]
        public void ImageSampleFilesTest()
        {
            // TODO unit test for the property 'ImageSampleFiles'
        }

    }

}
