/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Leap.Api;
using Leap.Model;
using Leap.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Leap.Test.Model
{
    /// <summary>
    ///  Class for testing InferenceEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InferenceEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InferenceEntity
        //private InferenceEntity instance;

        public InferenceEntityTests()
        {
            // TODO uncomment below to create an instance of InferenceEntity
            //instance = new InferenceEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InferenceEntity
        /// </summary>
        [Fact]
        public void InferenceEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" InferenceEntity
            //Assert.IsType<InferenceEntity>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'NegativePrompt'
        /// </summary>
        [Fact]
        public void NegativePromptTest()
        {
            // TODO unit test for the property 'NegativePrompt'
        }
        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Fact]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'PromptStrength'
        /// </summary>
        [Fact]
        public void PromptStrengthTest()
        {
            // TODO unit test for the property 'PromptStrength'
        }
        /// <summary>
        /// Test the property 'NumberOfImages'
        /// </summary>
        [Fact]
        public void NumberOfImagesTest()
        {
            // TODO unit test for the property 'NumberOfImages'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Fact]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Fact]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }
        /// <summary>
        /// Test the property 'UpscalingOption'
        /// </summary>
        [Fact]
        public void UpscalingOptionTest()
        {
            // TODO unit test for the property 'UpscalingOption'
        }

    }

}
