/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Leap.Api;
using Leap.Model;
using Leap.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Leap.Test.Model
{
    /// <summary>
    ///  Class for testing ListModelsV2Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListModelsV2ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListModelsV2Response
        //private ListModelsV2Response instance;

        public ListModelsV2ResponseTests()
        {
            // TODO uncomment below to create an instance of ListModelsV2Response
            //instance = new ListModelsV2Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListModelsV2Response
        /// </summary>
        [Fact]
        public void ListModelsV2ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListModelsV2Response
            //Assert.IsType<ListModelsV2Response>(instance);
        }


        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }

    }

}
