/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Leap.Api;
using Leap.Model;
using Leap.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Leap.Test.Model
{
    /// <summary>
    ///  Class for testing ModelV2Entity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelV2EntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelV2Entity
        //private ModelV2Entity instance;

        public ModelV2EntityTests()
        {
            // TODO uncomment below to create an instance of ModelV2Entity
            //instance = new ModelV2Entity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelV2Entity
        /// </summary>
        [Fact]
        public void ModelV2EntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelV2Entity
            //Assert.IsType<ModelV2Entity>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'SubjectKeyword'
        /// </summary>
        [Fact]
        public void SubjectKeywordTest()
        {
            // TODO unit test for the property 'SubjectKeyword'
        }
        /// <summary>
        /// Test the property 'SubjectType'
        /// </summary>
        [Fact]
        public void SubjectTypeTest()
        {
            // TODO unit test for the property 'SubjectType'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ImageSamples'
        /// </summary>
        [Fact]
        public void ImageSamplesTest()
        {
            // TODO unit test for the property 'ImageSamples'
        }

    }

}
