/*
 * Leap
 *
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Leap.Api;
using Leap.Model;
using Leap.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Leap.Test.Model
{
    /// <summary>
    ///  Class for testing MusicgenInferenceEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MusicgenInferenceEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MusicgenInferenceEntity
        //private MusicgenInferenceEntity instance;

        public MusicgenInferenceEntityTests()
        {
            // TODO uncomment below to create an instance of MusicgenInferenceEntity
            //instance = new MusicgenInferenceEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MusicgenInferenceEntity
        /// </summary>
        [Fact]
        public void MusicgenInferenceEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" MusicgenInferenceEntity
            //Assert.IsType<MusicgenInferenceEntity>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'MediaUri'
        /// </summary>
        [Fact]
        public void MediaUriTest()
        {
            // TODO unit test for the property 'MediaUri'
        }

    }

}
