/*
 * Leap
 * The Official Leap API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.leap.client.api;

import com.konfigthis.leap.client.ApiException;
import com.konfigthis.leap.client.ApiClient;
import com.konfigthis.leap.client.ApiException;
import com.konfigthis.leap.client.Configuration;
import java.io.File;
import com.konfigthis.leap.client.model.ListModelsV2Response;
import com.konfigthis.leap.client.model.ModelV2Entity;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImageModelsApi
 */
@Disabled
public class ImageModelsApiTest {

    private static ImageModelsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ImageModelsApi(apiClient);
    }

    /**
     * Delete a Model
     *
     * This endpoint will delete a model. This is not reversible.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteModelTest() throws ApiException {
        String modelId = null;
        ModelV2Entity response = api.deleteModel(modelId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a Single Model
     *
     * This endpoint will return a single model.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getModelTest() throws ApiException {
        String modelId = null;
        ModelV2Entity response = api.getModel(modelId)
                .execute();
        // TODO: test validations
    }

    /**
     * List All Models
     *
     * This endpoint will return a list of all models for the workspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllModelsTest() throws ApiException {
        ListModelsV2Response response = api.listAllModels()
                .execute();
        // TODO: test validations
    }

    /**
     * Train Model
     *
     * Upload a few image samples, and train a new model. Training usually takes 20-40 minutes. To be notified when the model completes training you must provide a &#x60;webhookUrl&#x60; in the training request, or check for completion by calling [Get a Single Model](https://reference.tryleap.ai/reference/get-model-1). After training completes, you can use the model to generate images with [Generate Images](https://reference.tryleap.ai/reference/inferencescontroller_create-1).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void trainModelTest() throws ApiException {
        String name = null;
        String subjectKeyword = null;
        String subjectType = null;
        String webhookUrl = null;
        List<String> imageSampleUrls = null;
        List<File> imageSampleFiles = null;
        ModelV2Entity response = api.trainModel()
                .name(name)
                .subjectKeyword(subjectKeyword)
                .subjectType(subjectType)
                .webhookUrl(webhookUrl)
                .imageSampleUrls(imageSampleUrls)
                .imageSampleFiles(imageSampleFiles)
                .execute();
        // TODO: test validations
    }

}
