# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from leap.type.model_v2_entity import ModelV2Entity

class RequiredListModelsV2Response(TypedDict):
    models: typing.List[ModelV2Entity]

class OptionalListModelsV2Response(TypedDict, total=False):
    pass

class ListModelsV2Response(RequiredListModelsV2Response, OptionalListModelsV2Response):
    pass
