# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import leap
from leap.model.create_inference_dto import CreateInferenceDto
from leap import configuration


class TestCreateInferenceDto(unittest.TestCase):
    """CreateInferenceDto unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
