# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import leap
from leap.model.inference_image_entity import InferenceImageEntity
from leap import configuration


class TestInferenceImageEntity(unittest.TestCase):
    """InferenceImageEntity unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
