# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import leap
from leap.model.music_controller_find_all_audio_response import MusicControllerFindAllAudioResponse
from leap import configuration


class TestMusicControllerFindAllAudioResponse(unittest.TestCase):
    """MusicControllerFindAllAudioResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
