# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import leap
from leap.model.inference_entity import InferenceEntity
from leap import configuration


class TestInferenceEntity(unittest.TestCase):
    """InferenceEntity unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
