# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import leap
from leap.model.create_and_train_model_dto import CreateAndTrainModelDto
from leap import configuration


class TestCreateAndTrainModelDto(unittest.TestCase):
    """CreateAndTrainModelDto unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
