# coding: utf-8

"""
    Leap

    The Official Leap API

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import leap
from leap.model.inferences_controller_find_all_response import InferencesControllerFindAllResponse
from leap import configuration


class TestInferencesControllerFindAllResponse(unittest.TestCase):
    """InferencesControllerFindAllResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
